def build(g):
 page,hero,section,cards,button=g['page'],g['hero'],g['section'],g['cards'],g['button']
 tools=[('pdf-watermark','PDF watermark','Add a text watermark to every page. Your PDF stays in your browser.'),('merge-pdf','Merge PDFs','Combine several PDFs in the order you choose.'),('bandwidth-calculator','Download bandwidth calculator','Estimate your monthly data transfer and a matching BIG plan.'),('custom-qr-code-generator','QR code generator','Turn a product or download-page link into a downloadable QR code.'),('custom-bulk-number-generator','Bulk number generator','Create unique random numeric codes and export them as CSV.'),('revenue-calculator','Digital product revenue calculator','Estimate contribution after discounts, fees and app costs.')]
 inner='<div class="site-grid">'+''.join(f'<a class="site-card site-blog-card" href="/tools/{slug}"><span class="site-kicker">Free tool</span><h3>{name}</h3><p>{desc}</p><span class="read">Open tool →</span></a>' for slug,name,desc in tools)+'</div>'
 page('/tools','Free Tools for Digital Product Sellers | BIG','Watermark or merge PDFs, create QR codes, generate numbers and estimate bandwidth or digital product revenue. Free tools that run in your browser.',hero('Free tools','Small tools.<br>Big help for your next launch.','Prepare your files and plan your sales. Free, no account required, with processing in your browser.',actions=False)+section('Built for digital sellers','Get something useful done.',inner))
 configs={
 'pdf-watermark':('''<label for="pdf-file">Your PDF (up to 50 MB)</label><input id="pdf-file" type="file" accept="application/pdf,.pdf" required><label for="watermark">Watermark text</label><input id="watermark" maxlength="120" value="Personal use only" required><div class="site-grid two"><div><label for="position">Position</label><select id="position"><option value="diagonal">Diagonal, centre of each page</option><option value="footer">Bottom of each page</option></select></div><div><label for="opacity">Opacity</label><select id="opacity"><option value="0.15">Light · 15%</option><option value="0.3" selected>Medium · 30%</option><option value="0.5">Strong · 50%</option></select></div></div><button class="site-button" type="submit">Watermark PDF</button>''','Add a visible reminder, not a false sense of security.','A watermark can discourage casual sharing. It does not encrypt the document or prevent screenshots. This tool applies the same text to every page; BIG’s in-app PDF stamping can personalise customer copies automatically.','pdf'),
 'merge-pdf':('''<label for="merge-files">Choose PDFs (up to 20 files, 50 MB total)</label><input id="merge-files" type="file" accept="application/pdf,.pdf" multiple required><div id="merge-order" class="site-notice" hidden></div><button class="site-button" type="submit">Merge PDFs</button>''','One file. In the right order.','After selecting your PDFs, use the up and down buttons to set their order. Originals remain unchanged. Password-protected PDFs are not supported. Document-level forms, attachments, bookmarks and signatures may not survive a merge.','pdf'),
 'bandwidth-calculator':('''<div class="site-grid two"><div><label for="file-mb">Average download size (MB)</label><input id="file-mb" type="number" min="0.01" max="1000000" step="any" value="100" required></div><div><label for="orders">Orders per month</label><input id="orders" type="number" min="0" max="100000000" step="1" value="1000" required></div><div><label for="downloads">Downloads per order</label><input id="downloads" type="number" min="1" max="1000" step="0.1" value="1.5" required></div><div><label for="storage">Total catalogue storage (GB)</label><input id="storage" type="number" min="0" max="1000000" step="any" value="10" required></div></div><label for="api"><input id="api" type="checkbox"> I need API access or webhooks</label><button class="site-button" type="submit">Estimate my usage</button>''','Storage is your shelf. Bandwidth is your delivery.','This estimate uses decimal units (1 GB = 1,000 MB; 1 TB = 1,000 GB), average completed downloads and repeat downloads. Actual usage can differ. It estimates BIG plan capacity, not a guaranteed invoice.',''),
 'custom-qr-code-generator':('''<label for="qr-text">Link or text to encode</label><textarea id="qr-text" maxlength="1500" rows="3" required>https://www.bigdigitaldownload.com</textarea><button class="site-button" type="submit">Create QR code</button><div id="qr-preview" aria-label="Generated QR code"></div>''','A shortcut to the right place.','Use a product page, public resource or help page. Avoid embedding a private customer download link in a public QR code. Scan the result on a second device before printing.','qr'),
 'custom-bulk-number-generator':('''<div class="site-grid two"><div><label for="code-count">Number of codes</label><input id="code-count" type="number" min="1" max="5000" step="1" value="100" required></div><div><label for="code-digits">Digits per code</label><input id="code-digits" type="number" min="4" max="24" step="1" value="12" required></div></div><label for="code-prefix">Optional prefix</label><input id="code-prefix" maxlength="12" pattern="[A-Za-z0-9_-]*" placeholder="BIG-"><button class="site-button" type="submit">Generate codes</button>''','Useful IDs, ready to export.','Codes are generated using your browser’s cryptographic random source and are unique within this batch. They are not automatically registered as Shopify discounts or software licences. Import and validate them in your own system. CSV cells are quoted to preserve leading zeroes in compatible importers.',''),
 'revenue-calculator':('''<div class="site-grid two"><div><label for="unit-price">Product price (USD)</label><input id="unit-price" type="number" min="0" step="0.01" value="25" required></div><div><label for="sales">Monthly orders</label><input id="sales" type="number" min="0" step="1" value="100" required></div><div><label for="discount">Average discount (%)</label><input id="discount" type="number" min="0" max="100" step="0.1" value="0" required></div><div><label for="fee-percent">Payment fee (%)</label><input id="fee-percent" type="number" min="0" max="100" step="0.01" value="2.9" required></div><div><label for="fee-fixed">Payment fee per order (USD)</label><input id="fee-fixed" type="number" min="0" step="0.01" value="0.30" required></div><div><label for="monthly-cost">Monthly app & other fixed costs (USD)</label><input id="monthly-cost" type="number" min="0" step="0.01" value="9.99" required></div></div><button class="site-button" type="submit">Calculate contribution</button>''','Plan with your own numbers.','The payment-fee values are editable examples, not a quoted Shopify rate. This is contribution before taxes, refunds, advertising and creation costs unless you include those costs yourself. It is not a forecast or accounting statement.','')}
 for slug,name,desc in tools:
  form,heading,note,lib=configs[slug]
  extra=('<script defer src="/assets/vendor/pdf-lib.min.js"></script>' if lib=='pdf' else '<script defer src="/assets/vendor/qrcode.min.js"></script>' if lib=='qr' else '')+'<script defer src="/assets/tools.js"></script>'
  body=f'<section class="site-section"><div class="site-wrap"><div class="site-breadcrumb"><a href="/">Home</a> / <a href="/tools">Free tools</a> / {name}</div><span class="site-kicker">Free · No account · In your browser</span><h1 style="font-size:clamp(36px,4vw,56px)">{name}</h1><p class="site-lead">{desc}</p><div class="site-editorial"><form class="site-card site-tool" id="tool-form" data-tool="{slug}">{form}<p class="tool-status" id="tool-status" role="status" aria-live="polite"></p><output id="tool-output" hidden></output><a id="tool-download" class="site-button orange" hidden download>Download</a></form><aside class="site-toc"><strong>{heading}</strong><p>{note}</p><a href="/tools">Browse all tools</a></aside></div></div></section>'+section('Next step','Ready to sell what you made?',f'<p class="site-lead">BIG handles delivery after a Shopify purchase, so you can focus on the next thing you create.</p>{button()}',soft=True)
  page('/tools/'+slug,name+' — Free Online Tool | BIG',desc+' No signup. Processed locally in your browser.',body,extra)
