import json,html

def build(g):
 data=json.loads((g['CONTENT']/'competitors.json').read_text());page,hero,section,button,cta=g['page'],g['hero'],g['section'],g['button'],g['cta'];esc=html.escape
 def logo(d,with_name=False):
  if d=='BIG':name='BIG Digital Downloads';src='/assets/media/3aed8c41fe6de0b62874.png'
  else:
   name=d['name'];f=next((g['DIST']/'assets/logos').glob(d['slug']+'.*'));src='/assets/logos/'+f.name
  img=f'<img class="app-logo" src="{src}" alt="{esc(name)}" width="48" height="48">'
  return '<span class="app-identity">'+img+('<span>'+esc(name)+'</span>' if with_name else '')+'</span>'
 def name_logo(name):
  if name in ['BIG','BIG Digital Downloads']:return logo('BIG',True)
  d=next((x for x in data if x['name']==html.unescape(name)),None)
  return logo(d,True) if d else name
 def cell(c):
  c=str(c)
  if c.startswith('✓'):return '<span class="feature-yes"><span class="orange-check">'+g['icon']('check')+'</span><span>'+c[1:].strip()+'</span></span>'
  if c.startswith('—'):return '<span class="feature-unknown"><span aria-hidden="true">—</span> '+c[1:].strip()+'</span>'
  return name_logo(c)
 def table(headers,rows):
  return '<div class="site-table-wrap" tabindex="0" role="region" aria-label="App comparison table"><table class="site-table"><thead><tr>'+''.join('<th scope="col">'+name_logo(x)+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td'+(' class="bdd"' if headers[i] in ['BIG','BIG Digital Downloads'] else '')+'>'+cell(c)+'</td>' for i,c in enumerate(r))+'</tr>' for r in rows)+'</tbody></table></div>'
 def compare_hero(d,alternative=False):
  name=esc(d['name']);slug=d['slug'];kind='Alternatives guide' if alternative else 'Shopify app comparison'
  title=name+'<br><em>alternatives.</em>' if alternative else 'BIG vs<br><em>'+name+'.</em>'
  lead='Find the right next app for your Shopify store. Compare workflows, capacity and the cost of your actual usage.' if alternative else d['intro']
  badges=logo(d)+'<span class="versus">→</span>'+logo('BIG') if alternative else logo('BIG')+'<span class="versus">vs</span>'+logo(d)
  return f'<section class="compare-hero"><div class="site-wrap"><div class="site-breadcrumb"><a href="/">Home</a> / <a href="/{"alternatives" if alternative else "compare"}">{kind}</a> / {name}</div><div class="comparison-intro"><div><span class="site-kicker">{kind} · 2026</span><h1>{title}</h1><p class="site-lead">{lead}</p><div class="comparison-meta">{g["icon"]("shield")} Official sources. Clear trade-offs.</div></div><div class="comparison-art"><img class="comparison-cover" src="/assets/editorial/{"alternatives" if alternative else "compare"}-{slug}.webp" width="1536" height="1024" alt="" fetchpriority="high"><div class="compare-logo-pair">{badges}</div></div></div><nav class="comparison-jumps" aria-label="On this page"><a href="#decision">The quick answer</a><a href="#features">Features & fit</a><a href="#pricing">Pricing & capacity</a><a href="#sources">Sources & migration</a></nav></div></section>'
 def publish_comparison(path,title,description,body):
  from bs4 import BeautifulSoup
  soup=BeautifulSoup(body,'html.parser')
  sections=soup.select('section.site-section:not(#final-cta)')
  ids=['decision','features','pricing']
  for sec,id in zip(sections,ids):sec['id']=id
  if sections:sections[-1]['id']='sources'
  page(path,title,description,str(soup))
 def links(d):return f'<a href="{d["source"]}" rel="noopener">{esc(d["name"])} · official Shopify listing</a>'+ (f' · <a href="{d["extraSource"]}" rel="noopener">Official pricing details</a>' if d.get('extraSource') else '')
 def methodology(d):return f'<div class="site-notice"><strong>How we compare</strong><p>Published by BIG Digital Downloads. Public product and pricing information reviewed on 22 September 2026; this is not an independent hands-on test. Monthly USD prices before tax, Shopify subscription fees and payment processing. Promotions and annual discounts excluded. A check means the source documents the capability; a dash means it is not stated, not that it is impossible.</p><p>Sources: {links(d)} · <a href="{g["APP"]}">BIG Shopify listing</a> · <a href="/#plans">BIG current plan details</a>.</p></div>'
 def comparison_card(d,alternative=False):
  path='/'+d['slug']+'-alternatives' if alternative else '/big-digital-downloads-vs-'+d['slug']
  return f'<a class="site-blog-card" href="{path}"><img loading="lazy" src="/assets/editorial/{"alternatives" if alternative else "compare"}-{d["slug"]}.webp" width="1536" height="1024" alt=""><div class="text"><div class="card-app-row">{logo(d)}<small>{"Alternatives guide" if alternative else "App comparison"}</small></div><h3>{esc(d["name"])}{" alternatives" if alternative else " vs BIG"}</h3><p>{d["focus"]}</p><span class="read">Explore the comparison →</span></div></a>'
 for d in data:
  name=esc(d['name']);slug=d['slug'];title='BIG Digital Downloads vs '+name
  body=compare_hero(d)
  body+=section('The decision in a minute','Which one fits your store?',f'<div class="site-grid two"><article class="site-card tint">{logo("BIG",True)}<span class="site-kicker">Choose BIG when</span><h3>Your Shopify delivery workflow comes first.</h3><p>{d["big"]}</p>{button()}</article><article class="site-card">{logo(d,True)}<span class="site-kicker">Choose {name} when</span><h3>{d["focus"]}.</h3><p>{d["other"]}</p><a href="{d["source"]}">Explore {name} on Shopify ↗</a></article></div>')
  rows=list(zip(['Automatic file delivery','Licence-key delivery','PDF watermark / stamping','Custom & scheduled products','Custom sender email','Imports / exports'],['✓ Available','✓ Available','✓ Paid plans','✓ Both workflows supported','✓ All paid plans','✓ Past orders; orders & keys exports'],d['features']))
  body+=section('Feature by feature','Compare the work you need to do.',table(['Capability','BIG Digital Downloads',name],rows)+'<p class="site-note">✓ Documented · — Not stated in the cited listing. Plan restrictions are shown where documented. This is not a checklist of every integration or feature.</p>',soft=True)
  body+=section('Monthly pricing','Know what changes your bill.',table(['Plan',name+' / month','Storage','Other published limits'],d['plans'])+'<p class="site-note">For BIG, Starter is $9.99 (15 GB / 50 GB transfer), Pro $19.99 (50 GB / 500 GB transfer), Growth $49.99 (1 TB / 1 TB), Enterprise $99.99 (unlimited storage / 1 TB + $0.023 per extra GB). Paid plans include unlimited orders.</p>')
  scenarios=[['First catalogue','50 orders · 1 GB stored · 5 GB transferred · $6,000 annual sales','Starter · $9.99',d['costs'][0]],['Growing download business','1,000 orders · 10 GB stored · 100 GB transferred · $120,000 annual sales','Pro · $19.99',d['costs'][1]],['Large digital library','3,000 orders · 200 GB stored · 600 GB transferred · $360,000 annual sales','Growth · $49.99',d['costs'][2]]]
  body+=section('Three example stores','The price depends on your usage.',table(['Monthly workload','Assumptions','BIG',name],scenarios)+f'<p class="site-note">Illustrative capacity comparisons, not like-for-like feature bundles. Annual revenue is used where a provider gates plans on revenue. These examples do not require streaming, subscriptions or API access. {d.get("costNote","")}</p><div class="site-notice"><strong>Before deciding</strong><p>{d["caution"]}</p></div><a href="/tools/bandwidth-calculator">Estimate your own download bandwidth →</a>',soft=True)
  if slug=='pdf-pendora':
   from pendora_evidence import section as evidence_section
   body+=evidence_section(g)
  body+=section('Make a clean switch','Test the journey, then migrate.', '<div class="site-grid"><div class="site-card"><span class="number">01</span><h3>Map what you sell</h3><p>Export your products, orders and keys where supported. Match each file to the correct product and variant. Keep an independent backup.</p></div><div class="site-card"><span class="number">02</span><h3>Test a real purchase</h3><p>Check email delivery, mobile download, PDF stamping and a previous customer’s access. Try the exact custom or scheduled workflow you intend to use.</p></div><div class="site-card"><span class="number">03</span><h3>Switch deliberately</h3><p>Disable duplicate delivery messages once tests pass. Monitor support requests and bandwidth during the first campaign. Keep the source app until access is verified.</p></div></div>'+methodology(d)+f'<p>Still exploring? <a href="/{slug}-alternatives">See {name} alternatives</a> or <a href="/compare">compare all nine apps</a>.</p>')+cta()
  publish_comparison('/big-digital-downloads-vs-'+slug,'BIG vs '+d['name']+': Features & Pricing (2026)',f'Compare BIG Digital Downloads and {d["name"]}: verified plans, feature differences, usage examples and who should choose each Shopify app.',body)
  others=[x for x in data if x['slug']!=slug]
  # Deliberately select different options based on the workflow, not a fabricated overall rank.
  best=[next(x for x in data if x['slug']==k) for k in ['fileflare','ldt-digital-downloads','sky-pilot','shopify-digital-downloads'] if k!=slug][:3]
  body=compare_hero(d,True)
  body+=section('The quick answer','Is BIG the right alternative?',f'<div class="site-grid two"><div class="site-card tint">{logo("BIG",True)}<h3>One place for your digital products.</h3><p>{d["big"]}</p><ul class="site-checks"><li>Standard, custom and scheduled delivery</li><li>Unlimited orders on paid plans</li><li>PDF stamping and licence-key delivery</li><li>Order imports and exports</li><li>Growth / Enterprise API and webhooks</li></ul>{button()}</div><div class="site-card">{logo(d,True)}<h3>When staying may make more sense.</h3><p>{d["other"]}</p><p>{d["caution"]}</p><a href="/big-digital-downloads-vs-{slug}">Read the full BIG vs {name} comparison →</a></div></div>',soft=True)
  body+=section('Start with the right question','What should your next app do better?',f'<p class="site-lead">{d["intro"]}</p><div class="site-grid"><article class="site-card"><span class="number">01</span><h3>Price the whole workload</h3><p>List your stored GB, transferred GB, monthly orders and required integrations. A low entry price is useful only if the plan supports those numbers.</p></article><article class="site-card"><span class="number">02</span><h3>List your non-negotiables</h3><p>Separate ordinary file delivery from PDF stamping, licence inventory, custom orders, scheduled releases and a true learning platform.</p></article><article class="site-card"><span class="number">03</span><h3>Protect existing access</h3><p>Check the migration path for previous buyers, old links, custom email templates and licence keys before cancelling your current subscription.</p></article></div>')
  rows=[['BIG Digital Downloads','$9.99 paid entry','15 GB storage / 50 GB monthly bandwidth','Shopify fulfilment, custom and scheduled products']]
  for x in best:
   paid=next((p for p in x['plans'] if p[1]!='$0'),x['plans'][0]);rows.append([esc(x['name']),paid[1],paid[2]+'; '+paid[3],x['focus']])
  body+=section('Other options worth a look','Different strengths. Clear trade-offs.',table(['App','Monthly entry plan','Included capacity','Consider it for'],rows)+'<p class="site-note">Entry tiers are shown for orientation, not equivalent feature bundles. Free plans may also be available. Follow each comparison for the full limits and source links.</p>'+'<div class="site-grid">'+''.join(comparison_card(x) for x in best)+'</div>')
  if slug=='pdf-pendora':
   from pendora_evidence import section as evidence_section
   body+=evidence_section(g)
  body+=section('Your migration checklist','Leave the friction behind.<br>Keep the customer experience.', '<div class="site-prose"><h3>Before you move</h3><p>Write down the exact problem with your current setup. If it is a support issue, get an answer before migrating; a move introduces work and can change customers’ links. If it is price, model at least your normal month and your largest promotion.</p><h3>During the trial</h3><p>Use a representative large file, one bundle, a licence-key product and a mobile test purchase where those apply. Test branded email delivery and ask what happens to historical orders. Check the public documentation for your required integration.</p><h3>At launch</h3><p>Back up your original files and exports. Verify order-to-file mappings. Stop duplicate delivery emails only after the new journey works, then monitor customer requests. Do not promise that old download URLs will survive a migration unless that has been verified.</p></div>'+methodology(d)+'<p>Additional option sources: '+ ' · '.join(links(x) for x in best)+'</p>')+cta()
  publish_comparison('/'+slug+'-alternatives',d['name']+' Alternatives for Shopify (2026) | BIG',f'Explore alternatives to {d["name"]} for Shopify digital products. Compare pricing, capacity, use cases and migration trade-offs with source links.',body)
 hub='<div class="site-grid">'+''.join(comparison_card(d) for d in data)+'</div>'
 page('/compare','Compare Shopify Digital Download Apps (2026) | BIG','Compare BIG with nine established Shopify digital product apps. Sourced features, prices and practical guidance for your store.',hero('Compare apps','A better fit starts<br>with a fair comparison.','Nine established apps. Real differences. Find the delivery workflow and capacity that make sense for your business.',actions=False)+section('Choose your comparison','Go beyond the starting price.',hub))
 page('/alternatives','Shopify Digital Download App Alternatives (2026)','Explore digital product app alternatives for Shopify, including Sky Pilot, Filemonk, Fileflare, EDP, SendOwl, LDT, FetchApp and more.',hero('Find an alternative','Your next app should<br>solve the right problem.','Explore options by the app you use today, with transparent trade-offs and practical migration advice.',actions=False)+section('Choose your starting point','What are you replacing?','<div class="site-grid">'+''.join(comparison_card(d,True) for d in data)+'</div>'))
 rows=[['BIG Digital Downloads','Free; paid from $9.99','Standard, custom and scheduled Shopify delivery']]+[[f'<a href="/big-digital-downloads-vs-{d["slug"]}">{esc(d["name"])}</a>',d['plans'][0][1]+' entry',d['focus']] for d in data]
 page('/best-shopify-digital-download-apps','Best Shopify Digital Download Apps for Your Use Case (2026)','A practical guide to ten Shopify digital product apps: compare fit, pricing, capacity and delivery workflows with official sources.',hero('Buying guide','The best app depends<br>on what you sell.','A merchant with a 5 MB ebook and a studio delivering gigabytes of video should not choose from the same price headline.',actions=False)+section('Shortlist by workflow','Ten apps to consider.',table(['App','Starting price','Primary consideration'],rows)+'<p class="site-note">Editorial selection of established apps, not a popularity ranking or independent benchmark. Published by BIG. Reviewed 22 September 2026.</p>')+section('Practical decisions','Start with these four questions.',g['cards']([('How large is your catalogue?','Count storage separately from monthly download transfer. Model repeat downloads and promotional spikes.'),('What must happen after payment?','A file link, a unique key, a personalised commission and a scheduled launch require different workflows.'),('What do customers need to view?','File delivery differs from streaming, an EPUB reader or a full course platform. Test on mobile.'),('Can you move your existing buyers?','Verify exports, old-order access, key inventory and duplicate emails before changing tools.')]))+section('Read the details','Compare BIG with each option.',hub))
