import json

def brand_section(g):
 names=[('plaud','PLAUD'),('star-wars','Star Wars'),('steal-a-brainrot','Steal a Brainrot'),('cupids','Cupids'),('dji','DJI')]
 logos=''
 for slug,name in names:
  files=list((g['DIST']/'assets/logos').glob(slug+'.*'))
  visual=f'<img src="/assets/logos/{files[0].name}" alt="{name}" loading="lazy" width="150" height="58">' if files else '<span>'+name+'</span>'
  logos+=f'<div class="customer-logo logo-{slug}">{visual}</div>'
 return '<section id="brand-proof" class="site-brands"><div class="site-wrap"><div class="brand-caption"><span class="mini-line"></span><p>Big names. Independent minds.<br><strong>In very good company.</strong></p><span class="mini-line"></span></div><div class="customer-logos">'+logos+'</div></div></section>'

def go_section(g):
 icon,button=g['icon'],g['button']
 categories=[('files','Ebooks & PDFs','/sell-ebooks-on-shopify'),('paint','Design & templates','/sell-canva-templates-on-shopify'),('key','Software & keys','/sell-license-keys-on-shopify'),('download','Music & video','/sell-music-on-shopify')]
 chips=''.join('<a href="'+path+'">'+icon(i)+'<span>'+n+'</span></a>' for i,n,path in categories)
 return f'''<section class="site-section go-section" id="go-to"><div class="site-wrap"><div class="go-layout"><div class="go-copy"><span class="site-kicker">Your store. Your possibilities.</span><h2>Whatever you create.<br><em>Make it a BIG thing.</em></h2><p class="site-lead">The digital downloads app for your Shopify store. Sell files, keys and custom creations from one place.</p>{button('Find your way to sell','/features')}</div><div class="go-art"><img src="/assets/editorial/features-digital-commerce.webp" width="1536" height="1024" alt="Ebooks, music, software and creative files ready for a digital store" loading="lazy"><span class="go-art-label">{icon('box')} One app. All your digital products.</span></div></div><div class="product-chip-row">{chips}</div><div class="audience-line"><span>For first-time creators.</span><span>For established brands.</span><span>For your next big idea.</span></div></div></section>'''

def mode_section(g):
 modes=[('download','Instant downloads','Ready when they are.','Ebooks, music, templates and software. Automatically delivered after checkout.','instant-downloads','Standard products'),('paint','Made to order','A little more personal.','Custom artwork, portraits and recordings. Deliver the finished creation when it’s ready.','custom-digital-products','Custom products'),('calendar','Scheduled releases','Good things are coming.','Preorders, album drops and launches. Release your files at a specific date and time.','scheduled-digital-releases','Scheduled products')]
 cards=''.join(f'<article class="delivery-card"><div class="delivery-image"><img src="/assets/design/{file}.webp" width="1536" height="1024" alt="" loading="lazy"><span>{g["icon"](ico)}{name}</span></div><div class="delivery-copy"><small>{label}</small><h3>{head}</h3><p>{text}</p></div></article>' for ico,name,head,text,file,label in modes)
 return f'<section class="site-section modes-section" id="product-modes"><div class="site-wrap"><div class="section-heading"><div><span class="site-kicker">Delivery, on your terms</span><h2>Three ways to sell.<br>One very happy customer.</h2></div><p>From instant downloads to something made just for them. Every product has its moment.</p></div><div class="delivery-grid">{cards}</div></div></section>'

def operations_section(g):
 icon=g['icon']
 return f'''<section class="site-section operations-section" id="operations"><div class="site-wrap"><div class="section-heading"><div><span class="site-kicker">The thoughtful little extras</span><h2>Looks like your brand.<br>Works like your business.</h2></div><a class="text-link" href="/features">Explore every feature {icon('arrow')}</a></div><div class="operations-grid"><article class="operation-email"><div><span class="feature-icon">{icon('email')}</span><h3>A delivery that feels like you.</h3><p>Your sender. Your colours. Your language.<br>Make every post-purchase moment your own.</p></div><div class="email-preview"><div class="email-chrome"><span>Delivery email</span><span>Preview</span></div><div class="email-content"><div class="email-store">YOUR STORE</div><span class="mail-ready">{icon('download')}</span><h4>A good thing just landed.</h4><p>Your digital order is ready to download.</p><span class="email-download">Get your files {icon('arrow')}</span><small>Thank you for supporting what we create.</small></div></div></article><div class="operations-side"><article><span class="feature-icon">{icon('files')}</span><div><h3>Bring your business with you.</h3><p>Import past orders. Export orders and licence keys. Keep your catalogue moving.</p><div class="operation-tags"><span>Past orders</span><span>Licence keys</span><span>Exports</span></div></div></article><article><span class="feature-icon">{icon('code')}</span><div><h3>Connect the dots.</h3><p>Connect your tools with the REST API and outgoing webhooks.</p><span class="plan-pill">Growth & Enterprise</span></div></article></div></div></div></section>'''

def journal_section(g):
 arts=json.loads((g['CONTENT']/'blog-manifest.json').read_text())
 preferred=['how-to-sell-digital-downloads-on-shopify-in-2026','how-to-sell-canva-templates-on-shopify-2026-step-by-step','how-to-protect-digital-products-from-piracy-on-shopify-(5-layers)']
 chosen=[next(a for a in arts if a['slug']==k) for k in preferred]
 cards=''.join(f'<a class="site-blog-card" href="/blog/{a["slug"]}"><img loading="lazy" src="/assets/editorial/blog--{a["slug"]}.webp" width="1536" height="1024" alt=""><div class="text"><small>{a["category"]} · {a["minutes"]} min read</small><h3>{a["title"]}</h3><span class="read">Read the story {g["icon"]("arrow")}</span></div></a>' for a in chosen)
 return f'<section class="site-section journal-section" id="learn"><div class="site-wrap"><div class="section-heading"><div><span class="site-kicker">The BIG journal</span><h2>Good ideas deserve<br>a great next step.</h2></div><a class="text-link" href="/blog">Explore all 40 guides {g["icon"]("arrow")}</a></div><div class="site-grid">{cards}</div></div></section>'


def trust_section(g):
 icon=g['icon']
 return f'''<section class="site-section trust-section" id="trust"><div class="site-wrap"><div class="trust-heading"><div><span class="site-kicker">A real business. Real people.</span><h2>Big on your business.<br><em>Personal about trust.</em></h2></div><p>Know who builds your app, how to reach us, and what’s in your control.</p></div><div class="trust-bento"><article class="trust-signature"><div class="trust-card-top"><span>INDEPENDENT BY DESIGN</span>{icon('spark')}</div><div class="trust-french-flag" aria-label="France"><span></span><span></span><span></span></div><h3>Built in France.<br>Built to be here.</h3><p>BIG is made by Penida SAS in Paris. An independent team, focused on the digital business you’re building.</p><div class="trust-signature-bottom"><span>Penida SAS<br><small>Paris, France</small></span><a href="/terms-and-conditions" aria-label="Read about Penida SAS">{icon('arrow')}</a></div></article><div class="trust-proof-stack"><article class="trust-verified"><div class="trust-seal">{icon('spark')}</div><div><span class="site-kicker">Built for Shopify</span><h3>The badge is theirs.<br>The experience is yours.</h3><p>Recognised through Shopify’s Built for Shopify programme. See what merchants say in their own words.</p><a class="text-link" href="{g['APP']}#reviews">Read merchant reviews {icon('arrow')}</a></div></article><article class="trust-support"><span class="feature-icon">{icon('help')}</span><div><h3>A real team on the other side.</h3><p>Questions about a launch, a file or a migration? Talk to us through the app.</p><a class="text-link" href="{g['DOCS']}">Get help from the team {icon('arrow')}</a></div></article></div><article class="trust-control"><div class="trust-control-heading"><span class="feature-icon">{icon('shield')}</span><div><span class="site-kicker">Your business, in your hands</span><h3>Protection you can see.<br>Information you can read.</h3></div></div><div class="trust-control-points"><div>{icon('check')}<span><strong>Discourage unauthorised sharing</strong><small>PDF stamping and download limits on paid plans.</small></span></div><div>{icon('check')}<span><strong>Keep your business portable</strong><small>Export your orders and licence keys.</small></span></div><div>{icon('check')}<span><strong>Understand how data is handled</strong><small>Our policies explain your rights and how to contact us.</small></span></div></div><div class="trust-policy-links"><a href="/privacy-policy">Privacy policy {icon('arrow')}</a><a href="/gdpr">Your data rights {icon('arrow')}</a></div><p class="trust-fine">PDF protection discourages sharing; it cannot make a downloaded file impossible to copy.</p></article></div></div></section>'''
